import { useMemo, useState } from 'react'
import { Activity, BookOpen, Check, ChevronRight, CircleHelp, Gauge, Github, Info, Leaf, Menu, Pause, Play, RotateCcw, ShieldCheck, SlidersHorizontal, Sparkles, Sun, Trophy, X } from 'lucide-react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis, LineChart, Line } from 'recharts'
import Scene from './Scene'
import { classify, simulate, systems, SystemId } from './engine'
import { useLab } from './store'

const pct = (v:number) => `${Math.round(v*100)}%`
function Metric({label,value,color}:{label:string,value:string,color?:string}) { return <div className="metric"><span>{label}</span><strong style={{color}}>{value}</strong></div> }

function App() {
  const {active, values, compare, reducedMotion, quizScore, setActive, setValue, toggleCompare, setReducedMotion, setQuizScore} = useLab()
  const [tab,setTab] = useState<'lab'|'compare'|'learn'>('lab')
  const [playing,setPlaying] = useState(true)
  const [quizOpen,setQuizOpen] = useState(false)
  const [menu,setMenu] = useState(false)
  const [viewMode,setViewMode] = useState<'Plant'|'Cutaway'|'Flow'|'Guided'|'Safety'|'Components'>('Plant')
  const system = systems.find(s=>s.id===active)!
  const series = useMemo(()=>simulate(values[active], systems.findIndex(s=>s.id===active)),[active,values])
  const latest = series[series.length-1]
  const riskState = classify(latest.risk)
  const selectSystem = (id:SystemId) => { setActive(id); setTab('lab'); setMenu(false) }
  return <div className="app-shell">
    <header className="topbar">
      <div className="brand"><div className="brand-mark"><Sparkles size={17}/></div><div><div className="brand-name">ENERGY SYSTEMS <span>LAB</span></div><div className="brand-sub">A safe, fictional learning studio</div></div></div>
      <nav className="desktop-nav" aria-label="Primary"><button className={tab==='lab'?'active':''} onClick={()=>setTab('lab')}><Activity size={16}/> Lab</button><button className={tab==='compare'?'active':''} onClick={()=>setTab('compare')}><SlidersHorizontal size={16}/> Compare <b>{compare.length}</b></button><button className={tab==='learn'?'active':''} onClick={()=>setTab('learn')}><BookOpen size={16}/> Field notes</button></nav>
      <div className="header-actions"><button className="icon-btn" title="Toggle reduced motion" aria-label="Toggle reduced motion" onClick={()=>setReducedMotion(!reducedMotion)}>{reducedMotion?<Pause size={17}/>:<Play size={17}/>}</button><button className="menu-btn" onClick={()=>setMenu(!menu)}><Menu size={20}/></button></div>
    </header>
    {menu && <div className="mobile-menu"><button onClick={()=>{setTab('lab');setMenu(false)}}>Lab</button><button onClick={()=>{setTab('compare');setMenu(false)}}>Compare systems</button><button onClick={()=>{setTab('learn');setMenu(false)}}>Field notes</button></div>}
    {tab==='learn' ? <Learn onQuiz={()=>setQuizOpen(true)}/> : tab==='compare' ? <Compare compare={compare} onSelect={selectSystem} /> : <main className="layout">
      <aside className="sidebar"><div className="eyebrow">SYSTEM INDEX <span>09</span></div><div className="system-list">{systems.map(s=><button key={s.id} className={active===s.id?'selected':''} onClick={()=>selectSystem(s.id)}><span className="dot" style={{background:s.color}}/><span><strong>{s.name}</strong><small>{s.kicker}</small></span><ChevronRight size={15}/></button>)}</div><div className="side-tip"><ShieldCheck size={17}/><span>All values are dimensionless. Learn the relationships, not the scale.</span></div></aside>
      <section className="workspace">
        <div className="hero-row"><div><div className="eyebrow" style={{color:system.color}}>{system.kicker.toUpperCase()} / SIMULATION 0{systems.findIndex(s=>s.id===active)+1}</div><h1>{system.name}</h1><p className="lede">{system.description}</p></div><div className="hero-actions"><button className="outline-btn" onClick={()=>toggleCompare(active)}>{compare.includes(active)?<Check size={15}/>:<SlidersHorizontal size={15}/>} {compare.includes(active)?'In compare':'Add to compare'}</button><button className="icon-btn" onClick={()=>setPlaying(!playing)} title={playing?'Pause simulation':'Play simulation'}>{playing?<Pause size={17}/>:<Play size={17}/>}</button></div></div>
        <div className="view-tabs" role="tablist" aria-label="Plant view modes">{(['Plant','Cutaway','Flow','Guided','Safety','Components'] as const).map(mode=><button key={mode} className={viewMode===mode?'active':''} onClick={()=>setViewMode(mode)}>{mode}</button>)}</div>
        <div className="research-label">RESEARCH CONCEPT · FICTIONAL PLANT MODEL · DIMENSIONLESS VALUES</div>
        <div className="lab-grid"><div className="scene-card"><Scene system={system} mode={viewMode}/><div className="scene-label"><span className="live-dot"/> {viewMode.toUpperCase()} VIEW <span className="scene-muted">• drag to orbit</span></div><div className="scene-caption"><span style={{background:system.color}}/> {system.name}<small>{playing?'running':'paused'} / 25 time steps</small></div></div>
          <div className="control-card"><div className="card-heading"><span>CONTROL DECK</span><Gauge size={17}/></div>{system.variables.map((label,i)=><label className="slider-row" key={label}><div><span>{label}</span><output>{values[active][i].toFixed(2)}</output></div><input aria-label={label} type="range" min="0" max="1" step=".01" value={values[active][i]} onChange={e=>setValue(active,i,+e.target.value)} style={{accentColor:system.color}}/></label>)}<div className="control-divider"/><button className="reset-btn" onClick={()=>values[active].forEach((_,i)=>setValue(active,i,[.62,.48,.7][i]))}><RotateCcw size={14}/> Reset variables</button><div className="safety-note"><Info size={15}/><span>Watch the risk indicator as variables move out of their stable envelope.</span></div></div></div>
        <div className="metrics-grid"><Metric label="NET OUTPUT" value={latest.output.toFixed(2)} color={system.color}/><Metric label="EFFICIENCY" value={pct(latest.efficiency)} color="#f5cf73"/><Metric label="SYSTEM RISK" value={riskState.toUpperCase()} color={riskState==='stable'?'#70e0c2':riskState==='watch'?'#f5cf73':'#fb7185'}/><Metric label="TIME STEP" value={`${latest.t}/25`} color="#b5c6d8"/></div>
        <div className="chart-card"><div className="chart-heading"><div><div className="eyebrow">OUTPUT TRACE</div><h2>Response over time</h2></div><div className={`status-pill ${riskState}`}><span/> {riskState==='stable'?'Stable envelope':riskState==='watch'?'Watch boundary':'Critical boundary'}</div></div><div className="chart-wrap"><ResponsiveContainer width="100%" height={210}><AreaChart data={series}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={system.color} stopOpacity={.35}/><stop offset="100%" stopColor={system.color} stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#1d3443" vertical={false}/><XAxis dataKey="t" tick={{fill:'#71879a',fontSize:11}} axisLine={false} tickLine={false}/><YAxis tick={{fill:'#71879a',fontSize:11}} axisLine={false} tickLine={false} domain={[0,1]}/><Tooltip contentStyle={{background:'#0d202e',border:'1px solid #294456',borderRadius:8}} labelStyle={{color:'#9eb2c2'}}/><Area type="monotone" dataKey="output" stroke={system.color} fill="url(#fill)" strokeWidth={2} name="Output"/></AreaChart></ResponsiveContainer></div></div>
        <div className="plant-notes"><div><span className="eyebrow">DIRECTED ENERGY FLOW</span><div className="flow-graph"><span>Source</span><b>→</b><span>{system.plant==='hybrid'?'PV bus':'Converter'}</span><b>→</b><span>Demand</span><i>surplus ↓ thermal store · residual heat after source shutdown</i></div><p>Thermal storage is modeled heat, not a battery or electrical store.</p></div><div><span className="eyebrow">COMPONENT INFO</span><strong>{viewMode==='Components'?'Tank, heat exchanger, bus and buffer':'Select Components for metadata'}</strong><p>Reusable plant primitives describe roles, not construction or operating parameters.</p></div></div>
        <div className="disclaimer"><ShieldCheck size={16}/><span>This simulator is fictional and for educational purposes only. It is not a design, safety, or operational tool.</span></div>
      </section>
    </main>}
    <footer><span>ENERGY SYSTEMS LAB <i>·</i> build 1.0</span><span>Dimensionless models <i>·</i> No real-world operating guidance</span><button onClick={()=>setQuizOpen(true)}><Trophy size={14}/> Take the 2-minute check</button></footer>
    {quizOpen && <Quiz close={()=>setQuizOpen(false)} score={quizScore} setScore={setQuizScore}/>}
  </div>
}

function Compare({compare,onSelect}:{compare:SystemId[],onSelect:(id:SystemId)=>void}) { const ids=compare.length?compare:systems.slice(0,3).map(s=>s.id); return <main className="compare-page"><div className="hero-row"><div><div className="eyebrow">SIDE-BY-SIDE STUDY</div><h1>Compare systems</h1><p className="lede">Place up to three fictional models next to each other and look for trade-offs.</p></div></div><div className="compare-grid">{ids.map(id=>{const s=systems.find(x=>x.id===id)!;const d=simulate([.62,.48,.7],systems.indexOf(s)).at(-1)!;return <button className="compare-card" key={id} onClick={()=>onSelect(id)}><div className="compare-icon" style={{background:s.accent,color:s.color}}><Sun size={22}/></div><div className="eyebrow" style={{color:s.color}}>{s.kicker}</div><h2>{s.name}</h2><p>{s.description}</p><div className="compare-stats"><Metric label="OUTPUT" value={d.output.toFixed(2)} color={s.color}/><Metric label="EFFICIENCY" value={pct(d.efficiency)} color="#f5cf73"/></div></button>})}</div><div className="compare-callout"><Sparkles size={17}/><span><strong>Study prompt:</strong> Which system has the smoothest output trace? What variable would you change first, and why?</span></div></main> }
function Learn({onQuiz}:{onQuiz:()=>void}) { return <main className="learn-page"><div className="eyebrow">FIELD NOTES / 01</div><h1>Learn by perturbing.</h1><p className="lede">Energy systems are stories about inputs, transformations, constraints, and trade-offs. Every model here uses invented units so you can focus on those relationships.</p><div className="learn-cards">{[['01','Inputs are never free','Every slider changes another part of the story. Look for the variable that creates the biggest response.'],['02','Boundaries matter','A stable envelope is not a guarantee. It is a useful prompt to ask what happens near the edge.'],['03','Compare before concluding','A high output can hide a low efficiency or a high risk. Use all three signals.']].map(([n,t,d])=><div className="learn-card" key={n}><span>{n}</span><h2>{t}</h2><p>{d}</p></div>)}</div><button className="primary-btn" onClick={onQuiz}><CircleHelp size={17}/> Check your understanding</button><div className="ethics"><Leaf size={22}/><div><strong>Designed for curiosity</strong><p>No actionable nuclear, fusion, or engineering guidance is presented. The named systems are fictional and dimensionless.</p></div></div></main> }
function Quiz({close,score,setScore}:{close:()=>void,score:number,setScore:(n:number)=>void}) { const [picked,setPicked]=useState<number|null>(null); const [done,setDone]=useState(false); const answer=1; return <div className="modal-backdrop" role="dialog" aria-modal="true"><div className="quiz-modal"><button className="close" onClick={close} aria-label="Close"><X size={18}/></button><div className="eyebrow">FIELD CHECK / 01</div><h2>What does the efficiency metric represent here?</h2><p>Remember: these systems are fictional. Think about the relationship, not a real-world unit.</p>{['The ratio of output to a modeled input','A guarantee that the system is safe','The physical size of the scene'].map((x,i)=><button className={`answer ${picked===i?'picked':''} ${done&&i===answer?'correct':''}`} key={x} onClick={()=>setPicked(i)}>{x}{done&&i===answer&&<Check size={16}/>}</button>)}{!done?<button className="primary-btn full" disabled={picked===null} onClick={()=>{setDone(true);if(picked===answer)setScore(score+1)}}>Check answer</button>:<div className="quiz-result">{picked===answer?'Nice work — you spotted the modeled relationship.':'Not quite. Efficiency is the ratio of useful output to modeled input.'}<button className="outline-btn" onClick={close}>Return to lab</button></div>}</div></div> }
export default App
